services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    ports:
      - "8080:8080"
    volumes:
      - /data/stirling-pdf/trainingData:/usr/share/tessdata
      - /data/stirling-pdf/extraConfigs:/configs
      - /data/stirling-pdf/logs:/logs
      - /data/stirling-pdf/pipeline:/pipeline
    environment:
      - SECURITY_ENABLELOGIN=false
      - LANGS=en_GB,en_US
      - SYSTEM_DEFAULTLOCALE=en-GB
      - UI_APPNAME=Stirling PDF
      - SYSTEM_MAXFILESIZE=100
      - METRICS_ENABLED=true
    restart: unless-stopped
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true