services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing
    hostname: media
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /data/syncthing/config:/var/syncthing/config
      - /data:/var/syncthing    # change to whatever that needs to be synced across devices
    ports:
      - 8384:8384         # Web UI
      - 22000:22000/tcp   # Sync protocol (TCP)
      - 22000:22000/udp   # Sync protocol (QUIC)
      - 21027:21027/udp   # Local discovery
    restart: unless-stopped
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true